<a href="https://colab.research.google.com/github/vishalsharma-jpg/StartingWithPython-ai1-fall2019/blob/master/mnist_keras_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# taken from lukas/ml-class
import numpy as np  
#used for all kinds of scientific calculation

from keras.datasets import mnist
#a set of data of handwrtten numbers provided by some organisation

from keras.models import Sequential
 
from keras.layers import Dense, Flatten, Dropout
# instead of  Dense, Flatten, Dropout we can also use "start"

from keras.utils import np_utils
from keras.callbacks import Callback
import json

# from wandb.keras import WandbCallback
# import wandb

# run = wandb.init()
# config = run.config




In [2]:
1+1 
  
   

2

In [0]:
class Config:
  #generally ehen we create aclass we have to write more code to enunciate the true meaning of that class
  #to avoid extra code, incase we don't have enough information about the kind of class we can simply write "pass".
  pass

config = Config()
config.optimizer = "adam"
#"adam " is the model consisting of various layers having functions like 2 relus and 1 softmax

config.epochs = 10
#how often we are going to perform adam on the test dataset 

config.hidden_nodes = 200
#means a total of 30 perceptrons are there in the intermediate layer



In [51]:
# load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()
#mnist people have come up with this idea of splitting the whole data of 70000
#data into 10000 test data and 60000 train data and this is how they do it
print(X_train.shape, y_train.shape)


img_width = X_train.shape[1]
img_height = X_train.shape[2]





(60000, 28, 28) (60000,)


In [46]:
y_train
#defining categories like 1234567890 to assign values to

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [0]:
#X_train = X_train.astype('float32')
#X_train /= 255.
#X_test = X_test.astype('float32')
#X_test /= 255.

# Normalize, change learning rate, play with layer size, batchsize

# one hot encode outputs
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
labels = range(10)

num_classes = y_train.shape[1]

In [37]:
y_train[0]
#

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [55]:
X_test

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [38]:
X_train[0]
#it is the array of the firts image fro the array of images x tarin

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [39]:
X_train[0,1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=uint8)

### Hello World
1. one
2.two
3.three

fcchjvxfzdgjgnvknnjfhfbkhcggxfg
- hello
- world

Hello the $\alpha$ is a greek letter
$$\alpha + \beta+ \gamma = \delta$$
---
---
**alpha**

In [53]:
# create model
model = Sequential()
model.add(Flatten(input_shape=(img_width, img_height)))
model.add(Dense(config.hidden_nodes, activation='relu'))
model.add(Dense(config.hidden_nodes, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer=config.optimizer,
              metrics=['accuracy'])
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_5 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_13 (Dense)             (None, 200)               157000    
_________________________________________________________________
dense_14 (Dense)             (None, 200)               40200     
_________________________________________________________________
dense_15 (Dense)             (None, 10)                2010      
Total params: 199,210
Trainable params: 199,210
Non-trainable params: 0
_________________________________________________________________


In [54]:

# Fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test),
          epochs=config.epochs)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 10s 172us/step - loss: 14.3193 - acc: 0.1115 - val_loss: 14.4612 - val_acc: 0.1028
Epoch 2/10
60000/60000 [==============================] - 10s 165us/step - loss: 14.4351 - acc: 0.1044 - val_loss: 14.4612 - val_acc: 0.1028
Epoch 3/10
60000/60000 [==============================] - 10s 166us/step - loss: 14.4351 - acc: 0.1044 - val_loss: 14.4612 - val_acc: 0.1028
Epoch 4/10
60000/60000 [==============================] - 10s 165us/step - loss: 14.4351 - acc: 0.1044 - val_loss: 14.4612 - val_acc: 0.1028
Epoch 5/10
60000/60000 [==============================] - 10s 165us/step - loss: 14.4351 - acc: 0.1044 - val_loss: 14.4612 - val_acc: 0.1028
Epoch 6/10
60000/60000 [==============================] - 10s 164us/step - loss: 14.4351 - acc: 0.1044 - val_loss: 14.4612 - val_acc: 0.1028
Epoch 7/10
60000/60000 [==============================] - 10s 166us/step - loss: 14.4351 - acc: 0.1044 -